const express = require("express");
const Report = require("../models/Report");

console.log("✅ STRICT REPORT ROUTES LOADED");

const router = express.Router();

const generateReportId = () => {
  return `REP${Date.now()}`;
};

const getErrorMessage = (error: any) => {
  if (error?.name === "ValidationError") {
    const firstError = Object.values(error.errors || {})[0] as any;
    return firstError?.message || "Validation failed";
  }

  if (error?.code === 11000) {
    return "Duplicate report data found";
  }

  return error?.message || "Something went wrong";
};

const isValidDate = (value: any) => {
  if (!String(value || "").trim()) return false;

  const date = new Date(value);
  return !Number.isNaN(date.getTime());
};

const validateReport = (body: any, isEdit = false) => {
  const title = body.title;
  const type = body.type;
  const totalRecords = body.totalRecords;
  const generatedBy = body.generatedBy;
  const generatedDate = body.generatedDate;
  const status = body.status;

  const allowedTypes = [
    "Employee",
    "Branch",
    "Customer",
    "Loan",
    "Transaction",
    "AI Risk",
    "Monthly Financial",
  ];

  const allowedStatuses = ["Ready", "Review", "Pending", "Archived"];

  if (!isEdit || title !== undefined) {
    if (!String(title || "").trim()) {
      return "Report title is required";
    }
  }

  if (!isEdit || type !== undefined) {
    if (!String(type || "").trim()) {
      return "Report type is required";
    }

    if (!allowedTypes.includes(type)) {
      return "Invalid report type";
    }
  }

  if (totalRecords !== undefined) {
    const numberValue = Number(totalRecords);

    if (Number.isNaN(numberValue)) {
      return "Total records must be a valid number";
    }

    if (numberValue < 0) {
      return "Total records cannot be negative";
    }
  }

  if (generatedBy !== undefined && !String(generatedBy || "").trim()) {
    return "Generated by is required";
  }

  if (!isEdit || generatedDate !== undefined) {
    if (!isValidDate(generatedDate)) {
      return "Generated date is required";
    }
  }

  if (status !== undefined && !allowedStatuses.includes(status)) {
    return "Invalid report status";
  }

  return "";
};

const normalizeReportPayload = (body: any) => {
  const payload: any = { ...body };

  if (payload.title !== undefined) {
    payload.title = String(payload.title || "").trim();
  }

  if (payload.totalRecords !== undefined) {
    payload.totalRecords = Number(payload.totalRecords || 0);
  }

  if (payload.generatedBy !== undefined) {
    payload.generatedBy = String(payload.generatedBy || "").trim();
  }

  return payload;
};

router.get("/", async (req: any, res: any) => {
  try {
    const reports = await Report.find({})
      .select("-_id -__v")
      .sort({ createdAt: -1 })
      .lean();

    return res.status(200).json({
      success: true,
      count: reports.length,
      data: reports,
    });
  } catch (error: any) {
    return res.status(500).json({
      success: false,
      message: "Failed to fetch reports",
      error: getErrorMessage(error),
    });
  }
});

router.post("/", async (req: any, res: any) => {
  try {
    const validationError = validateReport(req.body, false);

    if (validationError) {
      return res.status(400).json({
        success: false,
        message: validationError,
      });
    }

    const payload = normalizeReportPayload(req.body);

    const report = await Report.create({
      id: generateReportId(),
      title: payload.title,
      type: payload.type,
      totalRecords: payload.totalRecords || 0,
      generatedBy: payload.generatedBy || "Admin",
      generatedDate: payload.generatedDate,
      status: payload.status || "Ready",
    });

    const savedReport = await Report.findOne({ id: report.id })
      .select("-_id -__v")
      .lean();

    return res.status(201).json({
      success: true,
      message: "Report created successfully",
      data: savedReport,
    });
  } catch (error: any) {
    return res.status(400).json({
      success: false,
      message: getErrorMessage(error),
      error: getErrorMessage(error),
    });
  }
});

router.put("/:id", async (req: any, res: any) => {
  try {
    const { id } = req.params;

    const existingReport = await Report.findOne({ id });

    if (!existingReport) {
      return res.status(404).json({
        success: false,
        message: "Report not found",
      });
    }

    const validationError = validateReport(req.body, true);

    if (validationError) {
      return res.status(400).json({
        success: false,
        message: validationError,
      });
    }

    const updateData = normalizeReportPayload(req.body);

    const report = await Report.findOneAndUpdate({ id }, updateData, {
      new: true,
      runValidators: true,
      context: "query",
    })
      .select("-_id -__v")
      .lean();

    return res.status(200).json({
      success: true,
      message: "Report updated successfully",
      data: report,
    });
  } catch (error: any) {
    return res.status(400).json({
      success: false,
      message: getErrorMessage(error),
      error: getErrorMessage(error),
    });
  }
});

router.delete("/:id", async (req: any, res: any) => {
  try {
    const { id } = req.params;

    const report = await Report.findOneAndDelete({ id })
      .select("-_id -__v")
      .lean();

    if (!report) {
      return res.status(404).json({
        success: false,
        message: "Report not found",
      });
    }

    return res.status(200).json({
      success: true,
      message: "Report deleted successfully",
      data: report,
    });
  } catch (error: any) {
    return res.status(500).json({
      success: false,
      message: "Failed to delete report",
      error: getErrorMessage(error),
    });
  }
});

module.exports = router;